#!/usr/bin/python
#Filename: ficher

import gtk
import gtk.glade
import pygtk
import gobject
import time
import MySQLdb
import os
import funcoes
import tabelas

class Programa(object):
	
	GLADE_FILE = "/opt/ficher/graficos/grafico.glade"
	
	def __init__(self, *args):
		#Creating builder
		builder = gtk.Builder()
		#loading glade archive on builder
		builder.add_from_file(self.__class__.GLADE_FILE)
		#Connecting Signals
		builder.connect_signals(self)
		#Loading Window
		self.mainWindow = builder.get_object("janelaPrincipal")
		#Loading List
		self.lista = builder.get_object("lista")
		self.modeloConsulta = gtk.ListStore(str,str)
		self.lista.set_model(self.modeloConsulta)
		col0 = gtk.TreeViewColumn('Nome					', gtk.CellRendererText(), text=0)
		col1 = gtk.TreeViewColumn('Mattricula   ', gtk.CellRendererText(), text=1)
		self.lista.append_column(col0)
		self.lista.append_column(col1)
		self.con = MySQLdb.connect("localhost", "root", "tom")
		self.con.select_db("ficher")
		self.cursor = self.con.cursor()
		self.model = self.lista.get_model()
		funcoes.refresh(self.model)
		self.lista_selection = self.lista.get_selection()
		self.lista_selection.set_mode(gtk.SELECTION_SINGLE)
		#Loading Dialogs
		self.dialogo_confirma = builder.get_object("confirma")
		self.dialogo_erro1 = builder.get_object("dialogoErro1")
		self.dialogo_erro2 = builder.get_object("dialogoErro2")
		self.dialogo_ISDU_confirma = builder.get_object("IDSUconfirma")
		self.dialogo_ISDU_confirma1 = builder.get_object("IDSUconfirma1")
		self.dialogo_ISDU_error = builder.get_object("dialogo_ISDU_error")
		self.dialogo_sobre = builder.get_object("sobre")
		#entry's
		self.nome = builder.get_object("nome")
		self.mat = builder.get_object("matricula")
		self.email = builder.get_object("email")
		self.curso = builder.get_object("curso")
		self.senha = builder.get_object("senha")
		self.senhaTeste = builder.get_object("senhaTeste")
		self.senhamaster = builder.get_object("senhamaster")
		self.senhamaster1 = builder.get_object("senhamaster1")


	def on_cadastrar_clicked(self, *args):
		nome = self.nome.get_text()
		mat = self.mat.get_text()
		email = self.email.get_text()
		curso = self.curso.get_text()
		senha = self.senha.get_text()
		senhaTeste = self.senhaTeste.get_text()
		if (nome and mat and email and curso):
			if (senha == senhaTeste):
				self.dialogo_ISDU_confirma.show()
			else:
				self.dialogo_erro1.show()
		else:
			self.dialogo_erro2.show()
	def show(self):
		self.mainWindow.show()	
		self.lista.show()
		
	def gtk_JP_destroy(self, *args):
		gtk.main_quit()
	#DIALOGS
	#Confirmation dialog
	def on_confirma_ok_clicked(self, *args):
		self.dialogo_confirma.hide()
	
	def on_confirma_close(self, *args):
		self.dialogo_confirma.close()

	#Error Dialog 1
	def on_dialogoErro1_close(self, *args):
		self.dialogo_erro1.close()

	def on_erro1_ok_clicked(self, *args):
		self.dialogo_erro1.hide()
	
	def on_dialogoErro2_close(self, *args):
		self.dialogo_erro2.close()

	def on_erro2_ok_clicked(self, *args):
		self.dialogo_erro2.hide()
	
	def on_botao_sobre_clicked(self, *args):
		self.dialogo_sobre.show()

	def on_pagina_clicked(self, *args):
		os.system("firefox http://evertonfreitas.com &")
	
	def on_sobre_fechar_clicked(self, *args):
		self.dialogo_sobre.hide()

	def on_IDSUconfirma_ok1_clicked(self, *args):
		senhamestre1 = self.senhamaster1.get_text()
		if (senhamestre1 == "tom"):
			model, iter = self.lista_selection.get_selected()
			time.sleep(1.0)
			self.cursor.execute('delete from minicurso where nome= %s', model.get_value(iter,0))
			funcoes.refresh(self.model)
			self.dialogo_ISDU_confirma1.hide()
			self.dialogo_confirma.show()
		else: 
			self.dialogo_ISDU_error.show()
		self.dialogo_ISDU_confirma.hide()	
		
	
	#user confirmation dialog
	def on_ISDU_errorOK_clicked(self, *args):
		self.dialogo_ISDU_error.hide()

	#aqui e onde ele insere os dados no banco de dados
	def on_IDSUconfirma_ok_clicked(self, *args):
		senhamestre = self.senhamaster.get_text()
		if (senhamestre == "tom"):
			nome = self.nome.get_text()
			mat = self.mat.get_text()
			email = self.email.get_text()
			curso = self.curso.get_text()
			senha = self.senha.get_text()
			senhaTeste = self.senhaTeste.get_text()
			self.cursor.execute("insert into minicurso (nome, mat, email, curso) values (%s, %s ,%s ,%s)", (nome, mat, email, curso))
			self.con.commit()
			time.sleep(1.0)
			self.nome.set_text("")
			self.mat.set_text("")
			self.email.set_text("")
			self.curso.set_text("")
			self.senha.set_text("")
			self.senhaTeste.set_text("")
			self.senhamaster.set_text("")
			self.dialogo_confirma.show()
			funcoes.refresh(self.model)
		else: 
			self.dialogo_ISDU_error.show()
		self.dialogo_ISDU_confirma.hide()	
	#--- botao de Desligar
	def on_desligar_clicked(self, *args):
		gtk.main_quit()
	
	#--- botao de excluir da tabela

	def on_excluir_clicked(self, *args):
		self.dialogo_ISDU_confirma1.show()
		
	#--- Criando tabela xls
	
	def on_expXls_clicked(self, *args):
		tabelas.criar_tabela()				
		
if __name__ == "__main__":
	w = Programa()
	w.show()
	gtk.main()
